---
- name: packages update
  package:
    name: "*"
    state: latest

# yumの接続先を日本限定にする
- name: put japan only /etc/yum/pluginconf.d/fastestmirror.conf
  copy:
    src: "etc/yum/pluginconf.d/fastestmirror.conf"
    dest: "/etc/yum/pluginconf.d/fastestmirror.conf"
    owner: root
    group: root
    mode: 0644

- name: epel install
  package:
    name: epel-release
    state: present

- name: yum-cron install
  package:
    name: yum-cron
    state: present
  notify:
    - enable yum-cron
    - restart yum-cron

- name: yum-utils install
  package:
    name: yum-utils
    state: present

- name: /etc/yum/yum-cron.conf
  copy:
    src: etc/yum/yum-cron.conf
    dest: /etc/yum/yum-cron.conf
    owner: root
    group: root
    mode: 0644

- name: put /etc/cron.hourly/0yum-hourly.cron
  copy:
    src: etc/cron.hourly/0yum-hourly.cron
    dest: /etc/cron.hourly/0yum-hourly.cron
    owner: root
    group: root
    mode: 0755
